Lockpickers-United/lpu-belt-explorer

package.json
scripts/generateSitemap-xml.js
src/entries/Entry.jsx

added script to generate xml sitemap and added script to package.json

Generate XML sitemap

---

src/filters/FilterDisplay.jsx
src/filters/InlineFilterDisplay.jsx

- remove filter label from chips
- add "Belt" to belt filter chips in a smart way
- clean up spacing.

feat: improve inline filter display

---

scripts/exportHtml.js
src/resources/seo-template.html

Lets search engines differentiate version pages which currently have the same titles.

feat: seo pages: add version to html title for locks with related entries

---

src/entries/Entries.jsx
src/filters/InlineDisplaySpacer.jsx
src/filters/InlineFilterDisplay.jsx
src/filters/InlineHeaderDisplay.jsx
src/info/BeltRequirements.jsx

The header displays if one of your collection lists (Own, Picked, Recorded, Wishlist) is in the filter list. Either through the user/collection menu or through the filter panel.

feat: add header display when user collection list is displayed

---

src/info/InfoButton.jsx
src/info/InfoPage.jsx
src/resources/intro.md
src/routes/InfoRoute.jsx
src/routes/routes.jsx

- Create route and components for Information page
- Update InfoButton to bring up new page
- (Reduce header size in intro.md to prevent wrap on mobile)

Feat: Create route for Information page

---

src/nav/CollectionSubMenu.jsx
src/nav/MainMenu.jsx
src/nav/Nav.jsx

new main menu with sub-menu for collections.

feat: new main menu

---

src/glossary/Glossary.jsx
src/glossary/GlossaryEntry.jsx

- remove border line and reduce spacing between entries
- add borderBottom to intro
- lowercase the first character of the title/credit to make it (Photo by: AunthorName)

Small tweaks to glossary display

---

src/stats/BeltDistributionBar.jsx
src/stats/LockingMechanisms.jsx
src/stats/PhotoStats.jsx
src/stats/StatsMainPage.jsx

plus some minor responsive refinements

feat: add locking mechanism chart to stats page

---

src/data/brandBeltData.json
src/stats/BrandBeltWaffle.jsx

- add lock count to data json
- add tooltip

feat: add lock count tooltip to brand belt waffle chart

---

src/glossary/GlossarySearchBox.jsx
src/leaderboard/LeaderboardSearchBox.jsx
src/locks/LockListSearchBox.jsx

- Search Locks
- Search Glossary
- Search Leaderboard

usability - add context to search placeholder text

---

src/admin/CollectionsReportMain.jsx

realized there would be a conflict between the file in the project and the one on the server...

data: update collections json path for /admin

---

src/admin/SiteReportMain.jsx
src/stats/CollectionTopLocks.jsx
src/stats/StatsRoute.jsx

(and add update time to site report)

data: json update for collectionsSummary

---

src/admin/AdminStatsTable.jsx
src/admin/CollectionsReportMain.jsx
src/admin/SiteReportMain.jsx
src/admin/collectionsReport/TopLocks.jsx
src/stats/CollectionTopLocks.jsx
src/stats/StatsRoute.jsx

- additional data "topLocksFull" in json
- use in TopLocks to display standard adminTables
- update stats/CollectionTopLocks to use new data
- (will remove old "topLocksAll" from json after publish)

feat: add top locks to collectionsReport

---

src/app/ErrorFallback.jsx
src/app/Tracker.jsx

extraParams={{path: location.pathname}} wasn't working...

fix: add page param to querystring for error tracking

---

src/scorecard/ScorecardRow.jsx

feat: scorecard: display version text

---

src/leaderboard/CompareBeltBar.jsx
src/leaderboard/CompareDanStats.jsx
src/leaderboard/CompareSelect.jsx
src/leaderboard/Leaderboard.jsx
src/leaderboard/LeaderboardCompare.jsx
src/leaderboard/LeaderboardName.jsx

feat: Leaderboard Compare Black Belts.

---

src/resources/danImportHowTo.md
src/resources/dans.md

Update HowTo to reflect transition includes still using Dan Sheet

Update HowTo to reflect transition, dan sheets still active

---

src/admin/systemMessageAdmin/SystemMessageForm.jsx
src/app/AppContext.jsx
src/entries/CollectionButton.jsx
src/entries/RecordingControls.jsx
src/filters/SortTextButton.jsx
src/locks/CompactEntries.jsx
src/locks/Entries.jsx
src/misc/LoadingDisplaySmall.jsx
src/scorecard/ImportPreview.jsx
src/scorecard/ImportPreviewDisplay.jsx

Expose collection icons in Compact view

---

src/context/ScoringContext.jsx
src/scorecard/ScorecardDanStats.jsx
src/scorecard/ScorecardDataProvider.jsx
src/scorecard/ScorecardRoute.jsx
src/scorecard/scoring.js

scorecard BB header - add unique lock count

---

.github/workflows/pr.js.yml
README.md

Here's my first pass at updating the readme. Please tell me more sections and information to add (this PR or another)
The one outstanding question so far is what is `setup-husky.sh` for? I'm curious if it's leftover from something or does it need to be added to the readme

update readme to help new contributors
